### ISSUE TITLE
Invitations are not working: Uncaught TypeError: j(...).autocomplete is not a function

### ISSUE THREAD

**Issue by Retlawxx** [boonebgorges/invite-anyone#155]
I have the newest WordPress 4.9.1 and BuddyPress 2.9.2 and Invite Anyone 1.3.19.
I removed everything from my functions.php and deactivated every plugin expect BuddyPress and Invite Anyone… still, the users do not get any invitations.

I do get this error on the dev tool console on the sending invitation page from a group moderator/admin.

```
Uncaught TypeError: j(...).autocomplete is not a function
    at HTMLDocument.<anonymous> (group-invites-js.js?ver=4.7.8:22)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
```
It actually **works by commenting** the following line causing the error:
` a = j('#create-group-form #send-to-input, #send-invite-form #send-to-input').autocomplete(options);`
in `invite-anyone/group-invites/group-invites-js.js`

**Comment by boonebgorges** [comment]
Hi @Retlawxx - Thanks for the ticket!

Are you seeing the jquery.autocomplete script loaded in the DOM? It should be at wp-content/plugins/invite-anyone/group-invites/jquery.autocomplete/jquery.autocomplete.min.js, or something like that.

**Comment by Retlawxx** [comment]
Hi @boonebgorges Sorry for the late reply.
Yes it seems to be there: 
![autocomplete](https://user-images.githubusercontent.com/3471924/33520323-3787817c-d7b9-11e7-9bbf-b82572254172.png)

**Comment by Retlawxx** [comment]
I get a similar error also for the global search plugin in:
`buddypress-global-search/assets/js/invite-anyone/group-invites-js.js`

I tried to comment 	`a = j('#create-group-form #send-to-input, #send-invite-form #send-to-input').devbridgeAutocomplete(options);` But this time I keep getting the error also after emptying up all caches with W3 Total Cache

`Uncaught TypeError: j(...).devbridgeAutocomplete is not a function
    at HTMLDocument.<anonymous> (group-invites-js.js?ver=4.9.1:22)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
    at HTMLDocument.K (jquery.js:2)`

@boonebgorges Did you notice something similar or is this just me?

**Comment by boonebgorges** [comment]
Hm - I didn't write `buddypress-global-search` and wasn't aware that they were loading their own JS. I just tested invite-anyone alongside buddypress-global-search and it didn't throw the error you've described, but it could be worth toggling it, just to test whether it's the interaction between the two plugins that's causing the bug.

One of two things must be happening. (a) When you load invite-anyone's jquery.autocomplete file, it's not actually registering the plugin properly with jQuery, or (b) some script later in the page is somehow deregistering the plugin, or otherwise interfering with it. The only way you could really figure this out is by setting some breakpoints in your browser's JS console, and then checking at each breakpoint whether `jQuery.fn.autocomplete` is properly set (something like `typeof jQuery.fn.autocomplete` in your console, which should return "function").

**Comment by Retlawxx** [comment]
I will try it out @boonebgorges thanks.

**Comment by Retlawxx** [comment]
The problem was causes by the  [datatables](https://datatables.net/manual/installation) script in the footer. Using the datatables script in the header instead solved it 

`function my_javascripts() {
    wp_enqueue_script( 'script', get_template_directory_uri() . '/js/datatables.min.js', array ( 'jquery' ), 1.1, **false**);
}
add_action( 'wp_enqueue_scripts', 'my_javascripts' );`

**Comment by boonebgorges** [comment]
@Retlawxx Thanks very much for reporting back! Without forking the jQuery library and then namespacing it, I'm not sure that there's anything we can do to prevent against problems like this one.

I appreciate you circling back and sharing your findings.
