### ISSUE TITLE
Conflict in Buddy Boss Group Invite?

### ISSUE THREAD

**Issue by jimijon** [boonebgorges/invite-anyone#180]
Maybe it is some simple config.

But in a BuddyBoss group display there are now two tabs to "invite". The first is BuddyBoss's, (don't see how to turn that off) and the second is invite-anyone.

However tapping the the invite-anyone breaks the code. BUT, in a normal User Profile the invite-anyone is working great.

Thoughts?

**Comment by boonebgorges** [comment]
BuddyPress uses the slug 'send-invites' for its Send Invites tab. Invite Anyone removes this tab. BuddyBoss appears to use 'invite', so Invite Anyone's removal doesn't do anything. Try this:

```php
add_action(
	'bp_setup_nav',
	function() {
		if ( ! bp_is_group() ) {
			return;
		}

		bp_core_remove_subnav_item( groups_get_current_group()->slug, 'invite' );
	},
	20
);
```

I won't add this to Invite Anyone itself, because I don't declare support for BuddyBoss (they're the ones who claim compat with BP plugins) and I don't have the resources to keep up with their changes.

**Comment by jimijon** [comment]
@boonebgorges  what file might the above be found or edited? thanks, new to all this at the moment.

**Comment by boonebgorges** [comment]
You could add it to an mu-plugin or some other editable place in your installation. 

https://developer.wordpress.org/advanced-administration/plugins/mu-plugins/
https://permalinkmanager.pro/blog/how-to-add-php-snippet-to-wordpress-3-methods/ 

Be very careful - this is the kind of thing that could crash your installation if you use the wrong syntax.
